CREATE TABLE copy_execution_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    copy_trading_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    leader_id BIGINT NOT NULL,
    leader_trade_id VARCHAR(120) NOT NULL,
    action VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DETECTED',
    market_id VARCHAR(100) NOT NULL,
    outcome_index INT NULL,
    token_id VARCHAR(100) NULL,
    leader_price DECIMAL(20, 8) NULL,
    execution_price DECIMAL(20, 8) NULL,
    quantity DECIMAL(20, 8) NOT NULL DEFAULT 0,
    notional DECIMAL(20, 8) NOT NULL DEFAULT 0,
    reason VARCHAR(1000) NULL,
    order_id VARCHAR(100) NULL,
    source VARCHAR(30) NOT NULL DEFAULT 'unknown',
    event_time BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_copy_execution_event UNIQUE (copy_trading_id, leader_trade_id, action),
    INDEX idx_copy_execution_event_config_time (copy_trading_id, event_time),
    INDEX idx_copy_execution_event_order_id (order_id)
);
